name: Build & Publish UNF ICS (KBH & Lyngby)

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: "10 6,10,14,20 * * *"  # UTC: 01:10, 06:10, 11:10, 14:10, 16:10, 20:10

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger type and run time
        run: |
          echo "触发类型: $GITHUB_EVENT_NAME"
          echo "运行时间: $(date '+%Y-%m-%d %H:%M:%S')"
      - name: Set workflow run title
        run: |
          echo "设置运行标题"
          if [ "$GITHUB_EVENT_NAME" = "schedule" ]; then
            echo "run_title=定时触发 $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          elif [ "$GITHUB_EVENT_NAME" = "push" ]; then
            echo "run_title=推送触发 $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            echo "run_title=手动触发 $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          else
            echo "run_title=其他触发 $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
          fi
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clean dist before build
        run: |
          rm -rf dist

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dateutil

      # Fail fast if secrets missing (never echo real values)
      - name: Check required secrets exist
        env:
          UNF_USER: ${{ secrets.UNF_USER }}
          UNF_PASS: ${{ secrets.UNF_PASS }}
        run: |
          if [ -z "${UNF_USER}" ] || [ -z "${UNF_PASS}" ]; then
            echo "Missing UNF_USER/UNF_PASS secrets."
            exit 1
          fi

      - name: Update index.html with last update time
        run: |
          mkdir -p dist
          dt=$(date "+%Y-%m-%d %H:%M:%S")
          sed -i "s|<span id=\"last-update-utc\">.*</span>|<span id=\"last-update-utc\">UTC: $dt</span>|" index.html
          cp index.html dist/
          
      - name: Generate ICS feeds (KBH & Lyngby)
        env:
          UNF_USER: ${{ secrets.UNF_USER }}
          UNF_PASS: ${{ secrets.UNF_PASS }}
        run: |
          python unf_events_to_ics.py --out-dir dist --pages 5
          ls -lah dist

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
